import { pgTable, uuid, text, jsonb, smallint, timestamp } from 'drizzle-orm/pg-core';
import { organizations } from './organizations';
import { customers }     from './customers';
import { profiles }      from './organizations';

/**
 * customer_routines — Home Care prescriptions generated by specialists.
 * Steps stored as JSONB arrays: [{ productName, instruction }]
 * Locale: es | pt | en  (controls the PDF language)
 */
export const customerRoutines = pgTable('customer_routines', {
  id:                  uuid('id').primaryKey().defaultRandom(),
  organizationId:      uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  customerId:          uuid('customer_id').notNull().references(() => customers.id),
  createdByProfileId:  uuid('created_by_profile_id').notNull().references(() => profiles.id),
  locale:              text('locale').notNull().default('es'),
  title:               text('title').notNull().default('Home Care Routine'),
  /** [{ productName: string; instruction: string }] */
  morningSteps:        jsonb('morning_steps').notNull().default([]),
  afternoonSteps:      jsonb('afternoon_steps').notNull().default([]),
  nightSteps:          jsonb('night_steps').notNull().default([]),
  specialistNotes:     text('specialist_notes'),
  pdfStoragePath:      text('pdf_storage_path'),
  pdfVersion:          smallint('pdf_version').notNull().default(1),
  sentAt:              timestamp('sent_at', { withTimezone: true }),
  createdAt:           timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:           timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type CustomerRoutine    = typeof customerRoutines.$inferSelect;
export type NewCustomerRoutine = typeof customerRoutines.$inferInsert;
